# https://cheatsheet.dennyzhang.com/kubernetes-yaml-templates
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dummy-controller
    spec:
      containers:
      - name: dummy-controller
        image: gcr.io/xx
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
